//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.04 at 09:58:44 PM VET 
//


package org.tempuri.po;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Items complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Items">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sno" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="unitprice" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="totalcost" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="unitpricepaise" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="totalcostpaise" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Items", propOrder = {
    "sno",
    "description",
    "quantity",
    "denom",
    "unitprice",
    "totalcost",
    "unitpricepaise",
    "totalcostpaise"
})
public class Items {

    @XmlElement(required = true)
    protected String sno;
    @XmlElement(required = true)
    protected String description;
    protected float quantity;
    
    protected String denom;
    @XmlElement(required = true)
    protected String unitprice;
    @XmlElement(required = true)
    protected String totalcost;
    @XmlElement(required = true)
    protected String unitpricepaise;
    @XmlElement(required = true)
    protected String totalcostpaise;

    /**
     * Gets the value of the sno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSno() {
        return sno;
    }

    /**
     * Sets the value of the sno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSno(String value) {
        this.sno = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     */
    public float getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     */
    public void setQuantity(float value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the unitprice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitprice() {
        return unitprice;
    }

    /**
     * Sets the value of the unitprice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitprice(String value) {
        this.unitprice = value;
    }

    /**
     * Gets the value of the totalcost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalcost() {
        return totalcost;
    }

    /**
     * Sets the value of the totalcost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalcost(String value) {
        this.totalcost = value;
    }

    /**
     * Gets the value of the unitpricepaise property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitpricepaise() {
        return unitpricepaise;
    }

    /**
     * Sets the value of the unitpricepaise property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitpricepaise(String value) {
        this.unitpricepaise = value;
    }

    /**
     * Gets the value of the totalcostpaise property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalcostpaise() {
        return totalcostpaise;
    }

    /**
     * Sets the value of the totalcostpaise property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalcostpaise(String value) {
        this.totalcostpaise = value;
    }

	public String getDenom() {
		return denom;
	}

	public void setDenom(String denom) {
		this.denom = denom;
	}

}
