//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.04 at 09:58:44 PM VET 
//


package org.tempuri.po;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PurchaseOrderType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PurchaseOrderType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="vendorDetails" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ponumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="poDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="itemtotal" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="itemtotalpaise" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="packingForwarding" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="packingForwardingpaise" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="vatPercentage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="vatAmount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="vatAmountpaise" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="excisePecentage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="exciseAmount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="exciseAmountpaise" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="totalCost" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="totalCostpaise" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="paymentTerms" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="deliveryDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="insurance" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="supportDocuments" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="modeOfDispatch" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="specialConditions" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="qutrefno" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="refDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="items" type="{http://tempuri.org/po.xsd}Items" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PurchaseOrderType", propOrder = {
    "vendorDetails",
    "ponumber",
    "poDate",
    "itemtotal",
    "itemtotalpaise",
    "packingForwarding",
    "packingForwardingpaise",
    "vatPercentage",
    "vatAmount",
    "vatAmountpaise",
    "excisePecentage",
    "exciseAmount",
    "exciseAmountpaise",
    "gst",
    "gstAmount",
    "gstAmountpaise",
    "totalCost",
    "totalCostpaise",
    "paymentTerms",
    "deliveryDate",
    "insurance",
    "supportDocuments",
    "modeOfDispatch",
    "specialConditions",
    "qutrefno",
    "refDate",
    "items"
})
public class PurchaseOrderType {

    @XmlElement(required = true)
    protected String vendorDetails;
    @XmlElement(required = true)
    protected String ponumber;
    @XmlElement(required = true)
    protected String poDate;
    @XmlElement(required = true)
    protected String itemtotal;
    @XmlElement(required = true)
    protected String itemtotalpaise;
    @XmlElement(required = true)
    protected String packingForwarding;
    @XmlElement(required = true)
    protected String packingForwardingpaise;
    @XmlElement(required = true)
    protected String vatPercentage;
    @XmlElement(required = true)
    protected String vatAmount;
    @XmlElement(required = true)
    protected String vatAmountpaise;
    @XmlElement(required = true)
    protected String excisePecentage;
    @XmlElement(required = true)
    protected String exciseAmount;
    @XmlElement(required = true)
    protected String exciseAmountpaise;
    @XmlElement(required = true)
    protected String gst;
    @XmlElement(required = true)
    protected String gstAmount;
    @XmlElement(required = true)
    protected String gstAmountpaise;
    public String getGst() {
		return gst;
	}

	public void setGst(String gst) {
		this.gst = gst;
	}

	public String getGstAmount() {
		return gstAmount;
	}

	public void setGstAmount(String gstAmount) {
		this.gstAmount = gstAmount;
	}

	public String getGstAmountpaise() {
		return gstAmountpaise;
	}

	public void setGstAmountpaise(String gstAmountpaise) {
		this.gstAmountpaise = gstAmountpaise;
	}

	@XmlElement(required = true)
    protected String totalCost;
    @XmlElement(required = true)
    protected String totalCostpaise;
    @XmlElement(required = true)
    protected String paymentTerms;
    @XmlElement(required = true)
    protected String deliveryDate;
    @XmlElement(required = true)
    protected String insurance;
    @XmlElement(required = true)
    protected String supportDocuments;
    @XmlElement(required = true)
    protected String modeOfDispatch;
    @XmlElement(required = true)
    protected String specialConditions;
    @XmlElement(required = true)
    protected String qutrefno;
    @XmlElement(required = true)
    protected String refDate;
    @XmlElement(required = true)
    protected List<Items> items;

    /**
     * Gets the value of the vendorDetails property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVendorDetails() {
        return vendorDetails;
    }

    /**
     * Sets the value of the vendorDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVendorDetails(String value) {
        this.vendorDetails = value;
    }

    /**
     * Gets the value of the ponumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPonumber() {
        return ponumber;
    }

    /**
     * Sets the value of the ponumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPonumber(String value) {
        this.ponumber = value;
    }

    /**
     * Gets the value of the poDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPoDate() {
        return poDate;
    }

    /**
     * Sets the value of the poDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPoDate(String value) {
        this.poDate = value;
    }

    /**
     * Gets the value of the itemtotal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemtotal() {
        return itemtotal;
    }

    /**
     * Sets the value of the itemtotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemtotal(String value) {
        this.itemtotal = value;
    }

    /**
     * Gets the value of the itemtotalpaise property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemtotalpaise() {
        return itemtotalpaise;
    }

    /**
     * Sets the value of the itemtotalpaise property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemtotalpaise(String value) {
        this.itemtotalpaise = value;
    }

    /**
     * Gets the value of the packingForwarding property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPackingForwarding() {
        return packingForwarding;
    }

    /**
     * Sets the value of the packingForwarding property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPackingForwarding(String value) {
        this.packingForwarding = value;
    }

    /**
     * Gets the value of the packingForwardingpaise property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPackingForwardingpaise() {
        return packingForwardingpaise;
    }

    /**
     * Sets the value of the packingForwardingpaise property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPackingForwardingpaise(String value) {
        this.packingForwardingpaise = value;
    }

    /**
     * Gets the value of the vatPercentage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVatPercentage() {
        return vatPercentage;
    }

    /**
     * Sets the value of the vatPercentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVatPercentage(String value) {
        this.vatPercentage = value;
    }

    /**
     * Gets the value of the vatAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVatAmount() {
        return vatAmount;
    }

    /**
     * Sets the value of the vatAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVatAmount(String value) {
        this.vatAmount = value;
    }

    /**
     * Gets the value of the vatAmountpaise property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVatAmountpaise() {
        return vatAmountpaise;
    }

    /**
     * Sets the value of the vatAmountpaise property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVatAmountpaise(String value) {
        this.vatAmountpaise = value;
    }

    /**
     * Gets the value of the excisePecentage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExcisePecentage() {
        return excisePecentage;
    }

    /**
     * Sets the value of the excisePecentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExcisePecentage(String value) {
        this.excisePecentage = value;
    }

    /**
     * Gets the value of the exciseAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExciseAmount() {
        return exciseAmount;
    }

    /**
     * Sets the value of the exciseAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExciseAmount(String value) {
        this.exciseAmount = value;
    }

    /**
     * Gets the value of the exciseAmountpaise property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExciseAmountpaise() {
        return exciseAmountpaise;
    }

    /**
     * Sets the value of the exciseAmountpaise property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExciseAmountpaise(String value) {
        this.exciseAmountpaise = value;
    }

    /**
     * Gets the value of the totalCost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalCost() {
        return totalCost;
    }

    /**
     * Sets the value of the totalCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalCost(String value) {
        this.totalCost = value;
    }

    /**
     * Gets the value of the totalCostpaise property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalCostpaise() {
        return totalCostpaise;
    }

    /**
     * Sets the value of the totalCostpaise property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalCostpaise(String value) {
        this.totalCostpaise = value;
    }

    /**
     * Gets the value of the paymentTerms property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentTerms() {
        return paymentTerms;
    }

    /**
     * Sets the value of the paymentTerms property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentTerms(String value) {
        this.paymentTerms = value;
    }

    /**
     * Gets the value of the deliveryDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveryDate() {
        return deliveryDate;
    }

    /**
     * Sets the value of the deliveryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveryDate(String value) {
        this.deliveryDate = value;
    }

    /**
     * Gets the value of the insurance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInsurance() {
        return insurance;
    }

    /**
     * Sets the value of the insurance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInsurance(String value) {
        this.insurance = value;
    }

    /**
     * Gets the value of the supportDocuments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupportDocuments() {
        return supportDocuments;
    }

    /**
     * Sets the value of the supportDocuments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupportDocuments(String value) {
        this.supportDocuments = value;
    }

    /**
     * Gets the value of the modeOfDispatch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModeOfDispatch() {
        return modeOfDispatch;
    }

    /**
     * Sets the value of the modeOfDispatch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModeOfDispatch(String value) {
        this.modeOfDispatch = value;
    }

    /**
     * Gets the value of the specialConditions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecialConditions() {
        return specialConditions;
    }

    /**
     * Sets the value of the specialConditions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecialConditions(String value) {
        this.specialConditions = value;
    }

    /**
     * Gets the value of the qutrefno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQutrefno() {
        return qutrefno;
    }

    /**
     * Sets the value of the qutrefno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQutrefno(String value) {
        this.qutrefno = value;
    }

    /**
     * Gets the value of the refDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefDate() {
        return refDate;
    }

    /**
     * Sets the value of the refDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefDate(String value) {
        this.refDate = value;
    }

    /**
     * Gets the value of the items property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the items property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItems().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Items }
     * 
     * 
     */
    public List<Items> getItems() {
        if (items == null) {
            items = new ArrayList<Items>();
        }
        return this.items;
    }

}
